### ISSUE TITLE
bug report: manjario iso running on laptop close lid doesn't suspend

### ISSUE THREAD

**Issue by c0b** [manjaro/manjaroiso#48]
https://github.com/manjaro/manjaroiso/commit/8840750c11361bc363bc2edfcff7021f6c3fb704#commitcomment-18059391

Could you tell why set `HandleLidSwitch=ignore` ?? this has caused a problem of when run iso on laptop, close the laptop doesn't suspend

from `man 5 logind.conf` the default `HandleLidSwitch` is `suspend`

**Comment by philmmanjaro** [comment]
This branch is depreciated. Please check with our [new profiles](https://github.com/manjaro/manjaro-tools-iso-profiles).
